name: dogapi
description: Dog API client.
version: 1.0.0
homepage: https://github.com/thexxiv/dogapi-dart
repository: https://github.com/thexxiv/dogapi-dart
documentation: https://thexxiv.github.io/dogapi-dart

environment:
  sdk: '>=2.16.1 <3.0.0'
